### ISSUE TITLE
[버그] 유저 채팅 삭제시 ErrorResponseException 발생

### ISSUE THREAD

**Issue by key-del-jeeinho** [key-del-jeeinho/cacophony-spring-boot#6]
**버그 내용**
Cacophony 로 개발된 봇이 있는 서버에서, 유저가 채팅을 삭제할 경우, `ErrorResponseException` 이 발생합니다
- 로그 요약
  net.dv8tion.jda.api.exceptions.ErrorResponseException: 50035: Invalid Form Body
user_id
  \- NUMBER_TYPE_MAX: snowflake value should be less than or equal to 9223372036854775807.
user_id 의 snowflake 가 0~9223372036854775807 범위 바깥에 존재하는 것 같습니다

**환경 스펙**
| | |
|:--------------:|-------------------------------|
|       os       | windows                       |
|       ide      | intellij 2021.2.3             |
|   build tool   | gradle                        |
|   module name  | cacophony-spring-boot-starter |
| module version | 1.0.7-RELEASED                |

**콘솔 로그**
```
2021-10-31 14:20:36.460 ERROR 8728 --- [inWS-ReadThread] net.dv8tion.jda.api.JDA                  : One of the EventListeners had an uncaught exception

net.dv8tion.jda.api.exceptions.ErrorResponseException: 50035: Invalid Form Body
user_id
	- NUMBER_TYPE_MAX: snowflake value should be less than or equal to 9223372036854775807.
	at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:227) ~[JDA-4.3.0_324.jar:4.3.0_324]
	at net.dv8tion.jda.internal.requests.DeferredRestAction.complete(DeferredRestAction.java:172) ~[JDA-4.3.0_324.jar:4.3.0_324]
	at net.dv8tion.jda.api.requests.RestAction.complete(RestAction.java:633) ~[JDA-4.3.0_324.jar:4.3.0_324]
	at io.github.key_del_jeeinho.cacophony_lib.domain.command.manager.CommandInputManager.lambda$new$0(CommandInputManager.java:26) ~[cacophony-lib-1.0.7-RELEASE.jar:na]
	at io.github.key_del_jeeinho.cacophony_lib.domain.event.ListenerCaller.callEvent(ListenerCaller.java:31) ~[cacophony-lib-1.0.7-RELEASE.jar:na]
	at io.github.key_del_jeeinho.cacophony_lib.domain.event.repeater.ChatEventRepeater.callChatEvent(ChatEventRepeater.java:89) ~[cacophony-lib-1.0.7-RELEASE.jar:na]
	at io.github.key_del_jeeinho.cacophony_lib.domain.event.repeater.ChatEventRepeater.onGuildMessageDelete(ChatEventRepeater.java:50) ~[cacophony-lib-1.0.7-RELEASE.jar:na]
	at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:483) ~[JDA-4.3.0_324.jar:4.3.0_324]
	at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96) ~[JDA-4.3.0_324.jar:4.3.0_324]
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88) ~[JDA-4.3.0_324.jar:4.3.0_324]
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70) ~[JDA-4.3.0_324.jar:4.3.0_324]
	at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:160) ~[JDA-4.3.0_324.jar:4.3.0_324]
	at net.dv8tion.jda.internal.handle.MessageDeleteHandler.handleInternally(MessageDeleteHandler.java:61) ~[JDA-4.3.0_324.jar:4.3.0_324]
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36) ~[JDA-4.3.0_324.jar:4.3.0_324]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952) ~[JDA-4.3.0_324.jar:4.3.0_324]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839) ~[JDA-4.3.0_324.jar:4.3.0_324]
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817) ~[JDA-4.3.0_324.jar:4.3.0_324]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:991) ~[JDA-4.3.0_324.jar:4.3.0_324]
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) ~[nv-websocket-client-2.14.jar:na]
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) ~[nv-websocket-client-2.14.jar:na]
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) ~[nv-websocket-client-2.14.jar:na]
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) ~[nv-websocket-client-2.14.jar:na]
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[nv-websocket-client-2.14.jar:na]
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[nv-websocket-client-2.14.jar:na]
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[nv-websocket-client-2.14.jar:na]
Caused by: net.dv8tion.jda.api.exceptions.ContextException: null
	at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54) ~[JDA-4.3.0_324.jar:4.3.0_324]
	at net.dv8tion.jda.api.requests.Request.<init>(Request.java:71) ~[JDA-4.3.0_324.jar:4.3.0_324]
	at net.dv8tion.jda.api.requests.RestFuture.<init>(RestFuture.java:36) ~[JDA-4.3.0_324.jar:4.3.0_324]
	at net.dv8tion.jda.internal.requests.RestActionImpl.submit(RestActionImpl.java:209) ~[JDA-4.3.0_324.jar:4.3.0_324]
	at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:219) ~[JDA-4.3.0_324.jar:4.3.0_324]
	... 24 common frames omitted
```

**Comment by key-del-jeeinho** [comment]
오류가 발생하는원인으로 추정되는 코드를 발견하였습니다
```java
private void callChatEvent(User author, MessageChannel messageChannel, long messageId, String message, ChatEvent.EventType eventType, ChatType chatType) {
        UserDto user;
        //delete event 같이 author 가 존재하지 않는경우, id 를 -1로 초기화한다
        if(author != null)
            user = new UserDto(author.getIdLong());
        else user = new UserDto(-1);
        ...
}
```
ChatEventRepeater 에 존재하는 해당 메서드에서 author 가 null 일 경우, userdto 에 -1 을 대입합니다. 해당 메서드에서 author 가 null 일 경우중 하나가 ChatEvent.EventType 이 DELETE 인 이벤트를 중계할 경우 입니다.

다만, UserDto 에 -1 이 대입된다 하더라도 즉시 실제 JDA 의 User 로 치환되진 않으므로 해당 UserDto 를 사용하는 코드를 살펴봐야 할 것 같습니다

**Comment by key-del-jeeinho** [comment]
전술한 치환코드를 발견하였습니다
```java
public CommandInputManager(CommandManager commandManager, JDA jda) {
        this.commandManager = commandManager;
        this.jda = jda;
        when(
                onChat()
        ).doAction(
                (EventListener<ChatEvent>) event -> {
                    if(jda.retrieveUserById(event.getAuthor().getId()).complete().isBot()) return; //작성자가 bot 일경우

                    String chat = event.getMessage().getContent();
                    this.commandManager.execute(input(chat), event.getAuthor(), event.getChannel());
                }
        ).complete();
    }

```

CommandInputManager 의 생성자에 ChatEvent 를 받아 Event의 Type 을 확인하지 않은채로
```java
if(jda.retrieveUserById(event.getAuthor().getId()).complete().isBot()) return; 
```
구문을 통해 UserDto 를 JDA 를 통해 치환하고있습니다.
따라서, 만약 해당 Action 에 전달되는 이벤트의 Type 이 DELETE 일 경우, id 가 -1인 UserDto 를 JDA 를 통해 DiscordAPI 에 조회요청을 하고 있으므로, 버그가 발생합니다

**해결방법**
CommandInputManager 의 생성자에 존재하는 Flow 의 action 을 구성할 때 맨 처음에 EventType 이 WRITE 인지 검사합니다

**Comment by key-del-jeeinho** [comment]
`cacophony-lib:1.0.7-RELEASE_FIXED0.1` 및 `cacophoby-spring-boot-starter:RELEASE_FIXED0.2` 에서 해결되었습니다!
